// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRv-1UWInPOXZaHoVVGXEjztbCGRR7SI',
    appId: '1:564430022318:web:14682246509a47dcfa6f3f',
    messagingSenderId: '564430022318',
    projectId: 'awon2-a69f6',
    authDomain: 'awon2-a69f6.firebaseapp.com',
    storageBucket: 'awon2-a69f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Jr_d8HOnAcFS0fwyUo1Ca76dNHTwlTE',
    appId: '1:564430022318:ios:a050b7460d05617ffa6f3f',
    messagingSenderId: '564430022318',
    projectId: 'awon2-a69f6',
    storageBucket: 'awon2-a69f6.appspot.com',
    iosBundleId: 'com.example.awonProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Jr_d8HOnAcFS0fwyUo1Ca76dNHTwlTE',
    appId: '1:564430022318:ios:a050b7460d05617ffa6f3f',
    messagingSenderId: '564430022318',
    projectId: 'awon2-a69f6',
    storageBucket: 'awon2-a69f6.appspot.com',
    iosBundleId: 'com.example.awonProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvRv-1UWInPOXZaHoVVGXEjztbCGRR7SI',
    appId: '1:564430022318:web:f6cb161bf5739817fa6f3f',
    messagingSenderId: '564430022318',
    projectId: 'awon2-a69f6',
    authDomain: 'awon2-a69f6.firebaseapp.com',
    storageBucket: 'awon2-a69f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvH9RlLYexE-0RXa3OLckTXEyfU70SYzw',
    appId: '1:265342399885:android:334bc1219ce058ab8279c4',
    messagingSenderId: '265342399885',
    projectId: 'my-awon',
    storageBucket: 'my-awon.appspot.com',
  );

}